[package]
name = "blade-core"
version.workspace = true
edition.workspace = true
description.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ash = "0.37.3"
memoffset = "0.9.0"
glam = "0.24.2"
