[package]
name = "holy-cad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpu-allocator = "0.22.0"
env_logger = "0.10.0"
log = "0.4.17"
