[package]
name = "cad-rs"
version = "0.1.0"
edition = "2021"


[dependencies]
ash = "0.37.2"
gpu-allocator = "0.22.0"
env_logger = "0.10.0"
log = "0.4.17"
winit = "0.28.6"
softbuffer = "0.2.0"
bytemuck = "1.13.1"
ash-window = "0.12.0"
raw-window-handle = "0.5.2"
